In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_048c30274d2040b78af0dc08384d2c26 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='smcGpYE5_PHo2BOCe9Y55fRLz2aD6DamvSXhutPUPJ4c',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_048c30274d2040b78af0dc08384d2c26.get_object(Bucket='gandhi-donotdelete-pr-aow6aqmfklaa1z',Key='Sonar edited.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()



20KHZ_200KHZ  200KHZ_2MHZ  2MHZ_20MHZ  20MHZ_200MHZ  200MHZ_2000MHZ  \
0       0.11506      0.24981     0.59690       0.54099         0.17553   
1       0.18120      0.77810     0.36074       0.25250         0.07852   
2       0.24274      0.69525     0.58549       0.48369         0.16200   
3       0.05908      0.20185     0.38732       0.63428         0.30694   
4       0.15241      0.46516     0.53996       0.33635         0.09049   

   2000MHZ_2GHZ OBJECT  
0       0.01108      R  
1       0.00916      R  
2       0.01603      R  
3       0.00957      R  
4       0.00792      R

In [2]:
import numpy as np
import matplotlib as plt
print(len(dataset.columns))

7


In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset

20KHZ_200KHZ  200KHZ_2MHZ  2MHZ_20MHZ  20MHZ_200MHZ  200MHZ_2000MHZ  \
0         0.11506      0.24981     0.59690       0.54099         0.17553   
1         0.18120      0.77810     0.36074       0.25250         0.07852   
2         0.24274      0.69525     0.58549       0.48369         0.16200   
3         0.05908      0.20185     0.38732       0.63428         0.30694   
4         0.15241      0.46516     0.53996       0.33635         0.09049   
5         0.10742      0.72656     0.40263       0.35433         0.11061   
6         0.15114      0.33237     0.59969       0.47152         0.15838   
7         0.10251      0.42242     0.64033       0.24333         0.13011   
8         0.05817      0.34561     0.63844       0.28833         0.13613   
9         0.04578      0.18975     0.80795       0.19636         0.07752   
10        0.02627      0.10574     0.64931       0.54447         0.08005   
11        0.04092      0.27744     0.69145       0.32461         0.07412   
12        0.05095      0.39838     0.59291       0.20395         0.07745   
13        0.08909      0.32255     0.59409       0.47686         0.15806   
14        0.06608      0.31262     0.53542       0.39921         0.14018   
15        0.12913      0.40270     0.54229       0.60019         0.13802   
16        0.10652      0.26517     0.57489       0.58271         0.28012   
17        0.07158      0.46206     0.45975       0.48300         0.21505   
18        0.06432      0.31998     0.74057       0.56207         0.12470   
19        0.25732      0.67712     0.55703       0.19045         0.09030   
20        0.20865      0.38805     0.56794       0.67525         0.14982   
21        0.09774      0.43081     0.36350       0.79929         0.26983   
22        0.09613      0.20820     0.30924       0.74431         0.45254   
23        0.04874      0.23414     0.61665       0.52236         0.15197   
24        0.05696      0.14876     0.36934       0.65062         0.17424   
25        0.03064      0.13600     0.75396       0.59843         0.20975   
26        0.09909      0.47847     0.62573       0.17467         0.12054   
27        0.04873      0.43374     0.72837       0.24313         0.11566   
28        0.07082      0.47290     0.56024       0.34349         0.11991   
29        0.09387      0.37372     0.58909       0.15119         0.09446   
..            ...          ...         ...           ...             ...   
178       0.06308      0.25819     0.73458       0.35789         0.09518   
179       0.09758      0.31731     0.77146       0.38765         0.15614   
180       0.13990      0.41413     0.78911       0.33615         0.21311   
181       0.11046      0.35166     0.73963       0.41534         0.39845   
182       0.11752      0.42436     0.74824       0.42688         0.28494   
183       0.12282      0.42851     0.81525       0.42225         0.28917   
184       0.19577      0.45557     0.78812       0.31479         0.23098   
185       0.12972      0.45195     0.82363       0.37695         0.24957   
186       0.13211      0.32343     0.62144       0.39482         0.43466   
187       0.09905      0.27023     0.63169       0.29965         0.22844   
188       0.08317      0.25533     0.65294       0.29286         0.18982   
189       0.09756      0.28500     0.69206       0.27582         0.14391   
190       0.07235      0.25724     0.69551       0.30166         0.14937   
191       0.08179      0.24431     0.70737       0.26832         0.14526   
192       0.08421      0.24814     0.69560       0.25114         0.12751   
193       0.06999      0.21620     0.69992       0.30362         0.14761   
194       0.09244      0.26033     0.82021       0.24616         0.11037   
195       0.08300      0.32391     0.85677       0.18710         0.16158   
196       0.08933      0.35091     0.89118       0.16095         0.13809   
197       0.07604      0.30736     0.86056       0.19538         0.13693   
198       0.08597      0.29051     0.84941       0.17

In [5]:
X=dataset.iloc[:,0:6].values

In [6]:
X

array([[ 0.11506,  0.24981,  0.5969 ,  0.54099,  0.17553,  0.01108],
       [ 0.1812 ,  0.7781 ,  0.36074,  0.2525 ,  0.07852,  0.00916],
       [ 0.24274,  0.69525,  0.58549,  0.48369,  0.162  ,  0.01603],
       ..., 
       [ 0.09175,  0.17556,  0.79874,  0.29309,  0.08165,  0.00932],
       [ 0.10162,  0.21514,  0.79234,  0.2214 ,  0.10205,  0.00568],
       [ 0.07835,  0.23791,  0.81887,  0.25058,  0.11501,  0.00855]])

In [7]:
y = dataset.iloc[:,-1].values

In [8]:
y

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M

In [9]:
#encode the dependent variable containing categorical values
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [10]:
encoder.fit(y)

LabelEncoder()

In [11]:
y = encoder.transform(y)

In [12]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [13]:
#transform the data in training and testing
from sklearn.utils import shuffle
X,y = shuffle(X,y,random_state=1)

In [14]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(X,y,test_size=0.20, random_state=42)

In [15]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
train_x =sc.fit_transform(train_x)
test_x = sc.transform(test_x)

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [17]:
keras.__version__

'2.1.4'

In [18]:
model=Sequential()

In [19]:
train_x.shape

(166, 6)

In [20]:
train_y.shape

(166,)

In [21]:
model.add(Dense(input_dim=6,init="random_uniform",activation='relu',output_dim=15))#input layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=15, kernel_initializer="random_uniform", activation="relu", input_dim=6)`
  if __name__ == '__main__':


In [22]:
model.add(Dense(output_dim=8,init="random_uniform",activation='relu'))#hidden layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="random_uniform", units=8, activation="relu")`
  if __name__ == '__main__':


In [23]:
model.add(Dense(output_dim=1,init='random_uniform',activation='sigmoid'))#output layer

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="random_uniform", units=1, activation="sigmoid")`
  if __name__ == '__main__':


In [24]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#adam=batch gradent descent

In [25]:
#train_y.reshape(1,-1)
train_y.shape

(166,)

In [26]:
model.fit(train_x,train_y,epochs=108, batch_size=83)#epochs no of iteration 

Epoch 1/108
166/166 [==============================] - 0s 664us/step - loss: 0.6931 - acc: 0.4578
Epoch 2/108
166/166 [==============================] - 0s 30us/step - loss: 0.6930 - acc: 0.5361
Epoch 3/108
166/166 [==============================] - 0s 21us/step - loss: 0.6930 - acc: 0.5361
Epoch 4/108
166/166 [==============================] - 0s 21us/step - loss: 0.6929 - acc: 0.5361
Epoch 5/108
166/166 [==============================] - 0s 25us/step - loss: 0.6928 - acc: 0.5361
Epoch 6/108
166/166 [==============================] - 0s 20us/step - loss: 0.6927 - acc: 0.5361
Epoch 7/108
166/166 [==============================] - 0s 22us/step - loss: 0.6927 - acc: 0.5361
Epoch 8/108
166/166 [==============================] - 0s 374us/step - loss: 0.6926 - acc: 0.5361
Epoch 9/108
166/166 [==============================] - 0s 24us/step - loss: 0.6925 - acc: 0.5361
Epoch 10/108
166/166 [==============================] - 0s 22us/step - loss: 0.6924 - acc: 0.5361
Epoch 11/108
166/166 [=====

166/166 [==============================] - 0s 26us/step - loss: 0.5479 - acc: 0.7711
Epoch 84/108
166/166 [==============================] - 0s 22us/step - loss: 0.5456 - acc: 0.7711
Epoch 85/108
166/166 [==============================] - 0s 424us/step - loss: 0.5430 - acc: 0.7711
Epoch 86/108
166/166 [==============================] - 0s 23us/step - loss: 0.5403 - acc: 0.7711
Epoch 87/108
166/166 [==============================] - 0s 23us/step - loss: 0.5382 - acc: 0.7711
Epoch 88/108
166/166 [==============================] - 0s 22us/step - loss: 0.5354 - acc: 0.7711
Epoch 89/108
166/166 [==============================] - 0s 22us/step - loss: 0.5331 - acc: 0.7711
Epoch 90/108
166/166 [==============================] - 0s 23us/step - loss: 0.5307 - acc: 0.7711
Epoch 91/108
166/166 [==============================] - 0s 20us/step - loss: 0.5284 - acc: 0.7711
Epoch 92/108
166/166 [==============================] - 0s 21us/step - loss: 0.5261 - acc: 0.7711
Epoch 93/108
166/166 [==========

In [27]:
y_pred = model.predict(test_x)

In [28]:
y_pred=(y_pred>0.5)

In [29]:
y_pred

array([[ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True]], dtype=bool)

In [30]:
test_y

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1])

In [48]:
y_p=model.predict(sc.transform(np.array([[0.04708,0.23187,0.56334,0.4592,0.11611,0.00494]])))

In [49]:
y_p

array([[ 0.9324683]], dtype=float32)

In [33]:
y_p=(y_p>0.4999607)

In [34]:
y_p

array([[ True]], dtype=bool)

In [35]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(test_y,y_pred)
print(cm)

[[20  2]
 [ 4 16]]


In [36]:

from sklearn.metrics import accuracy_score
accuracy_score(test_y, y_pred)

0.8571428571428571

In [37]:
model.save("projects.h5")

In [38]:
import os
cwd = os.getcwd()
cwd

'/home/dsxuser/work'

In [39]:
!tar -zcvf projects.tgz projects.h5

projects.h5


In [40]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [41]:
wml_credentials={
    "url": "https://eu-gb.ml.cloud.ibm.com",
    "instance_id": "e1f71393-defe-402f-948e-a1a2b9914e02",
    "username": "b9c424e1-f4b7-4798-9fae-68d2ce88ce37",
    "password": "bc54ef99-dee5-41ed-9958-625494961f35",
     "access_key": "_SdcBeC8ZGvinPVi3hduq7cNfmZJMuU50hp8igQ-u-FV"
}

In [42]:
Client = WatsonMachineLearningAPIClient(wml_credentials)

In [43]:
metadata={
Client.repository.ModelMetaNames.NAME: "keras",
Client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES: [{'name':'keras','version': '2.1.3'}],
Client.repository.ModelMetaNames.FRAMEWORK_VERSION: '1.5',
Client.repository.ModelMetaNames.FRAMEWORK_NAME: "tensorflow"
}

In [44]:
model_details=Client.repository.store_model(model="projects.tgz",meta_props=metadata)

In [45]:
model_id=model_details["metadata"]["guid"]
model_deployment_details=Client.deployments.create(artifact_uid=model_id,name='deployment')



#######################################################################################

Synchronous deployment creation for uid: 'e21d4e03-21e6-4556-946a-2f333a3ad901' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='73f12bdd-68aa-4b15-a3d1-a8f65fffb5d5'
------------------------------------------------------------------------------------------------




In [46]:
scoring_endpoint=Client.deployments.get_scoring_url(model_deployment_details)

In [47]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/e1f71393-defe-402f-948e-a1a2b9914e02/deployments/73f12bdd-68aa-4b15-a3d1-a8f65fffb5d5/online'